"""Add progress and status to Video table

Revision ID: 74364fb9fdd1
Revises: b35ea9f78fd1
Create Date: 2024-09-28 08:25:52.189062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74364fb9fdd1'
down_revision: Union[str, None] = 'b35ea9f78fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('progress', sa.Float(), nullable=False))
    op.add_column('video', sa.Column('status', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'status')
    op.drop_column('video', 'progress')
    # ### end Alembic commands ###
