"""Add video table

Revision ID: b35ea9f78fd1
Revises: 
Create Date: 2024-09-28 04:52:35.273186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b35ea9f78fd1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('detected_url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_detected_url'), 'video', ['detected_url'], unique=False)
    op.create_index(op.f('ix_video_id'), 'video', ['id'], unique=False)
    op.create_index(op.f('ix_video_name'), 'video', ['name'], unique=False)
    op.create_index(op.f('ix_video_url'), 'video', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_url'), table_name='video')
    op.drop_index(op.f('ix_video_name'), table_name='video')
    op.drop_index(op.f('ix_video_id'), table_name='video')
    op.drop_index(op.f('ix_video_detected_url'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
