"""Add table scene

Revision ID: b3755e96870f
Revises: 1b855573749f
Create Date: 2024-09-29 03:05:35.385709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b3755e96870f'
down_revision: Union[str, None] = '1b855573749f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('video_id', sa.UUID(), nullable=False),
                    sa.Column('start_timecode', sa.Float(), nullable=False),
                    sa.Column('end_timecode', sa.Float(), nullable=False),
                    sa.Column('start_frame', sa.BigInteger(), nullable=False),
                    sa.Column('end_frame', sa.BigInteger(), nullable=False),
                    sa.Column('start_fps', sa.Float(), nullable=False),
                    sa.Column('end_fps', sa.Float(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('text_emotion', sa.Text(), nullable=False),
                    sa.Column('audio_emotion', sa.Text(), nullable=False),
                    sa.Column('image_emotion', sa.Text(), nullable=False),
                    sa.Column('scene_emotion', sa.Text(), nullable=False),
                    sa.Column('main_emotion', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scene_id'), 'scene', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_id'), table_name='scene')
    op.drop_table('scene')
    # ### end Alembic commands ###
