"""emotionnsupport

Revision ID: f09da1faa561
Revises: b3755e96870f
Create Date: 2024-09-29 12:43:52.233171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09da1faa561'
down_revision: Union[str, None] = 'b3755e96870f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('text_emotion', sa.Text(), nullable=False))
    op.add_column('scene', sa.Column('audio_emotion', sa.Text(), nullable=False))
    op.add_column('scene', sa.Column('image_emotion', sa.Text(), nullable=False))
    op.add_column('scene', sa.Column('scene_emotion', sa.Text(), nullable=False))
    op.add_column('scene', sa.Column('main_emotion', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'main_emotion')
    op.drop_column('scene', 'scene_emotion')
    op.drop_column('scene', 'image_emotion')
    op.drop_column('scene', 'audio_emotion')
    op.drop_column('scene', 'text_emotion')
    # ### end Alembic commands ###
