"""Add nullable detected_url

Revision ID: fc4a174e1fd7
Revises: f7c204998003
Create Date: 2024-09-28 08:46:40.113460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4a174e1fd7'
down_revision: Union[str, None] = 'f7c204998003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'detected_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'detected_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
