FROM python:3.12-slim


WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY versions/ ./versions/

COPY ./alembic.ini ./config.py ./database.py ./env.py ./models.py /app

CMD ["alembic", "upgrade", "head"]
